### ISSUE TITLE
expose labels

### ISSUE THREAD

**Issue by orkwizard** [emrade/flutter-cool-stepper#1]
Would be good have exposed the labels "BACK" "NEXT" and "STEP OF" to be easily changed to support any languaje or different texts people would like to have.

**Comment by emrade** [comment]
Thanks for the suggestion @orkwizard.

I just released a new version 1.1.0, it contains the suggestion you just made.

The CoolStepper class now has a new property called config which is of type CoolStepperConfig.
It has properties like backText, nextText .

Something like 

```
CoolStepperConfig(
  backText: "BACK",
  nextText: "NEXT",
  stepText: "STEP",
  ofText: "OF",
);
```

I hope that helps.
