### ISSUE TITLE
Validation issues with Null Safety

### ISSUE THREAD

**Issue by Purus** [emrade/flutter-cool-stepper#11]
Based on dart's null-safety feature, we can not return null for the validation method. So this is breaking in new version of dart beta.

**Comment by joaovvrodrigues** [comment]
I edited the code and am returning a String, 'null'. And it works normally ... It is not the most correct method, but not to interfere with the package logic, it worked.

If you want to try using it, just do the following, but I added another dependency, flushbar, which may not be pleasant for you. But I believe that this package has been discontinued, if it is very important for your project, as it is for mine, I recommend that you do something similar.

![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-03-08 at 10 15 37](https://user-images.githubusercontent.com/31359621/110326436-6c90a300-7ff7-11eb-8705-b52658904f3f.png)

`  cool_stepper:`
`    git:`
`      url: https://github.com/joaovvrodrigues/flutter-cool-stepper`

![Captura de Tela 2021-03-08 às 10 16 13](https://user-images.githubusercontent.com/31359621/110326447-71555700-7ff7-11eb-8196-c40312e93656.png)

**Comment by lcsvcn** [comment]
@joaovvrodrigues Can you open a PR?

**Comment by joaovvrodrigues** [comment]
@lcsvcn I can, but I think this package has been discontinued. If you want to use it as I taught above and any problem you find, comment with me that I can fix, in my tests everything worked OK.

**Comment by emrade** [comment]
Thanks to @joaovvrodrigues a new version with Null Safety and Flushbar has been released.
