### ISSUE TITLE
Handle Custom Click Functionality for next button

### ISSUE THREAD

**Issue by rt16** [emrade/flutter-cool-stepper#4]
Is it possible to give our own functionality when the next button is clicked.

**Comment by emrade** [comment]
I'm sorry @rt16 that feature is not available right now. But I will consider adding it to future releases.

**Comment by emrade** [comment]
@rt16 Actually,  you can run your own functions inside  the validation property of each CoolStep. 
Like

```
CoolStep(
        title: "Select your role",
        subtitle: "Choose a role that better defines you",
        content: Container(),
        validation: () {
          doSomething();
          return null;
        },
      ),
```
I hope that helps you
