### ISSUE TITLE
Validation method in CoolStep can be used for prevent the user come back in the steps?

### ISSUE THREAD

**Issue by viniciushenr** [emrade/flutter-cool-stepper#8]
The validation method in the CoolStep are used by the verification if the condition for the actual step are satisfated, if if not, the user not can be going to the next step.

In my case, i need to prevent to the user come back in the steps, by pressing the "Back" button. Is there some way to do that?

Thank you for anyone how want to help me with this issue.

**Comment by emrade** [comment]
Sorry @viniciushenr there is no way to do that currently!
